"""Database stasiun LRT Jakarta koridor Kelapa Gading (Pegangsaan Dua) - Manggarai.

Nama stasiun menggunakan nama resmi 2026 (Lin Selatan / Lin Kelapa Gading LRT Jakarta).
Kunci = kode stasiun resmi (KPG, BVU, BVS, PUM, EQS, VEL, RWM, PRM, PSM, MTR-LRT...).
"""

STATIONS = {
    "KPG": {
        "stop_id": "KPG",
        "stop_code": "KPG",
        "stop_name": "KELAPA GADING LRT",
        "stop_lat": -6.157589,
        "stop_lon": 106.914076,
        "zone_id": "JAKARTA UTARA",
        "level_id": "L0",
        "is_active": 1,
    },
    "BVU": {
        "stop_id": "BVU",
        "stop_code": "BVU",
        "stop_name": "BOULEVARD UTARA LRT",
        "stop_lat": -6.159400,
        "stop_lon": 106.906005,
        "zone_id": "JAKARTA UTARA",
        "level_id": "L0",
        "is_active": 1,
    },
    "BVS": {
        "stop_id": "BVS",
        "stop_code": "BVS",
        "stop_name": "BOULEVARD SELATAN LRT",
        "stop_lat": -6.168990,
        "stop_lon": 106.899996,
        "zone_id": "JAKARTA UTARA",
        "level_id": "L0",
        "is_active": 1,
    },
    "PUM": {
        "stop_id": "PUM",
        "stop_code": "PUM",
        "stop_name": "PULOMAS LRT",
        "stop_lat": -6.184100,
        "stop_lon": 106.891300,
        "zone_id": "JAKARTA TIMUR",
        "level_id": "L0",
        "is_active": 1,
    },
    "EQS": {
        "stop_id": "EQS",
        "stop_code": "EQS",
        "stop_name": "EQUESTRIAN LRT",
        "stop_lat": -6.184059,
        "stop_lon": 106.891269,
        "zone_id": "JAKARTA TIMUR",
        "level_id": "L0",
        "is_active": 1,
    },
    "VEL": {
        "stop_id": "VEL",
        "stop_code": "VEL",
        "stop_name": "VELODROME LRT",
        "stop_lat": -6.192581,
        "stop_lon": 106.891210,
        "zone_id": "JAKARTA TIMUR",
        "level_id": "L0",
        "is_active": 1,
    },
    "RWM": {
        "stop_id": "RWM",
        "stop_code": "RWM",
        "stop_name": "RAWAMANGUN LRT",
        "stop_lat": -6.193230,
        "stop_lon": 106.883670,
        "zone_id": "JAKARTA TIMUR",
        "level_id": "L0",
        "is_active": 1,
    },
    "PRM": {
        "stop_id": "PRM",
        "stop_code": "PRM",
        "stop_name": "PRAMUKA LRT",
        "stop_lat": -6.196500,
        "stop_lon": 106.872000,
        "zone_id": "JAKARTA TIMUR",
        "level_id": "L0",
        "is_active": 1,
    },
    "PSM": {
        "stop_id": "PSM",
        "stop_code": "PSM",
        "stop_name": "PROKLAMASI LRT",
        "stop_lat": -6.201000,
        "stop_lon": 106.865000,
        "zone_id": "JAKARTA TIMUR",
        "level_id": "L0",
        "is_active": 1,
    },
    "MRT": {
        "stop_id": "MRT",
        "stop_code": "MRT",
        "stop_name": "MATRAMAN LRT",
        "stop_lat": -6.195062,
        "stop_lon": 106.859983,
        "zone_id": "JAKARTA TIMUR",
        "level_id": "L0",
        "is_active": 1,
    },
    "MRI": {
        "stop_id": "MRI",
        "stop_code": "MRI",
        "stop_name": "MANGGARAI LRT",
        "stop_lat": -6.208638,
        "stop_lon": 106.845758,
        "zone_id": "JAKARTA SELATAN",
        "level_id": "L0",
        "is_active": 1,
    },
}